#!/usr/bin/env bash
# Adds disposable display-boundary data through Quoin's public Admin API.
# It is intentionally opt-in: run it only after recording the empty-state view.
# It never prints credentials or reveal handles, and it refuses any non-#96 URL.
set -euo pipefail

repo_root=$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)
runtime_root=${QUOIN_E2E_RUNTIME:-"${repo_root}/.artifacts/e2e-real"}
credentials_file="${runtime_root}/credentials.yaml"
[[ -f "$credentials_file" ]] || { printf 'Start the disposable environment first: scripts/e2e-real/up.sh\n' >&2; exit 1; }
readarray -t credential_values < <(python3 - "$credentials_file" <<'PY'
# credentials.yaml is generated by up.sh in this fixed, three-value format.
# Parse only those scalar fields rather than loading arbitrary YAML objects.
import sys
values = {}
for line in open(sys.argv[1], encoding="utf-8"):
    key, separator, value = line.strip().partition(": ")
    if separator and key in {"url", "username", "password"}:
        values[key] = value
for key in ("url", "username", "password"):
    if key not in values:
        raise SystemExit(f"missing {key} in generated credentials.yaml")
    print(values[key])
PY
)
QUOIN_E2E_URL=${credential_values[0]}
QUOIN_E2E_ADMIN_USERNAME=${credential_values[1]}
admin_final=${QUOIN_E2E_ADMIN_FINAL_PASSWORD:-${credential_values[2]}}
case "${QUOIN_E2E_URL}" in https://localhost:*) ;; *) printf 'Refusing non-disposable URL: %s\n' "${QUOIN_E2E_URL}" >&2; exit 1;; esac
jar=$(mktemp)
trap 'rm -f "$jar"' EXIT
login_status=$(curl --silent --show-error --insecure --output /dev/null --write-out '%{http_code}' \
  --cookie-jar "$jar" --header "Origin: ${QUOIN_E2E_URL}" --header 'Content-Type: application/json' \
  --data "$(jq -nc --arg username "$QUOIN_E2E_ADMIN_USERNAME" --arg password "$admin_final" '{username:$username,password:$password}')" \
  "${QUOIN_E2E_URL}/api/v1/auth/login")
[[ "$login_status" == 200 ]] || { printf 'Admin login failed (%s). Complete initial password change in the UI or set QUOIN_E2E_ADMIN_FINAL_PASSWORD.\n' "$login_status" >&2; exit 1; }

# Keys are deterministic for idempotent reruns; existing keys return 409 and are
# counted as already available. The final key deliberately tests long text.
for index in $(seq 1 50); do
  key=$(printf 'boundary-%02d' "$index")
  if [[ "$index" == 50 ]]; then
    key="boundary-50-$(printf 'very-long-alertmanager-source-name-'%.0s {1..5})"
  fi
  command="boundary-create-${index}-96"
  status=$(curl --silent --show-error --insecure --output /dev/null --write-out '%{http_code}' \
    --cookie "$jar" --header "Origin: ${QUOIN_E2E_URL}" --header 'Content-Type: application/json' \
    --data "$(jq -nc --arg key "$key" --arg command "$command" '{key:$key,protocol:"alertmanager",clientCommandId:$command}')" \
    "${QUOIN_E2E_URL}/api/v1/alert-sources")
  case "$status" in 201|409) ;; *) printf 'Creating %s failed (%s).\n' "$key" "$status" >&2; exit 1;; esac
done
printf 'Prepared 50 disposable Alertmanager instances at %s.\n' "$QUOIN_E2E_URL"
