import { useEffect, useRef, useState } from "react";
import { Alert, AlertDescription } from "@/components/ui/alert";
import { Button } from "@/components/ui/button";
import { Field, FieldDescription, FieldLabel } from "@/components/ui/field";
import { Input } from "@/components/ui/input";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { newClientCommandId, notifyUnauthorized } from "../../api";

type Backup = { id: string; status: string; stage: string; createdAt: string; updatedAt: string; sizeBytes: number; errorDetail?: string };
type BackupPage = { items?: Backup[]; nextCursor?: string; retentionHealth?: { lastFailureAt?: string; errorDetail?: string } };
type BackupSettings = { enabled: boolean; scheduleCron?: string | null; timezone: string; backupTarget: string; retentionCount: number; rowVersion: number };
type ArtifactRetention = { generatedRetentionDays: number; rowVersion: number };
class BackupError extends Error { constructor(readonly status: number, message: string) { super(message); } }
const text = (reason: unknown) => reason instanceof Error ? reason.message : "暂时无法完成操作，请重试。";
const active = (value: Backup) => ["queued", "running", "pending"].includes(value.status.toLowerCase());
async function request<T>(path: string, init?: RequestInit): Promise<T> {
  const response = await fetch(path, { credentials: "include", headers: init?.body ? { "Content-Type": "application/json", ...init.headers } : init?.headers, ...init });
  if (!response.ok) { if (response.status === 401) notifyUnauthorized(); let body: { message?: string; detail?: string } = {}; try { body = await response.json() as typeof body; } catch { /* fallback */ } throw new BackupError(response.status, body.message ?? body.detail ?? "暂时无法完成操作，请重试。"); }
  return response.status === 204 ? undefined as T : response.json() as Promise<T>;
}

/** Backups are asynchronous server tasks; this view never invents restore or cancellation commands. */
export function Backups({ suspended }: { suspended: boolean }) {
  const [items, setItems] = useState<Backup[]>([]); const [cursor, setCursor] = useState<string>(); const [settings, setSettings] = useState<BackupSettings>(); const [retention, setRetention] = useState<ArtifactRetention>(); const [error, setError] = useState(""); const [saving, setSaving] = useState(false); const poll = useRef<number | undefined>(undefined);
  const load = async (more = false) => {
    try { const page = await request<BackupPage>(`/api/v1/backups?limit=50${more && cursor ? `&cursor=${encodeURIComponent(cursor)}` : ""}`); setItems(current => more ? [...current, ...(page.items ?? [])] : page.items ?? []); setCursor(page.nextCursor); const [nextSettings, nextRetention] = await Promise.all([request<BackupSettings>("/api/v1/backups/settings"), request<ArtifactRetention>("/api/v1/artifacts/retention-settings")]); setSettings(nextSettings); setRetention(nextRetention); if (page.retentionHealth?.lastFailureAt) setError(`旧备份清理失败，将自动重试：${page.retentionHealth.errorDetail ?? "无详情"}`); } catch (reason) { setError(text(reason)); }
  };
  useEffect(() => { void load(); }, []);
  useEffect(() => { window.clearInterval(poll.current); if (!suspended && items.some(active)) poll.current = window.setInterval(() => void load(), 3000); return () => window.clearInterval(poll.current); }, [suspended, items]);
  async function trigger() { try { await request<Backup>("/api/v1/backups", { method: "POST", body: JSON.stringify({ clientCommandId: newClientCommandId() }) }); await load(); } catch (reason) { setError(text(reason)); } }
  async function saveSettings(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); if (!settings) return; setSaving(true); try { setSettings(await request<BackupSettings>("/api/v1/backups/settings", { method: "PUT", body: JSON.stringify({ clientCommandId: newClientCommandId(), expectedRowVersion: settings.rowVersion, enabled: settings.enabled, scheduleCron: settings.scheduleCron || null, timezone: settings.timezone, retentionCount: settings.retentionCount }) })); } catch (reason) { setError(reason instanceof BackupError && reason.status === 409 ? "备份设置已被其他管理员修改，请刷新后重试。" : text(reason)); } finally { setSaving(false); } }
  async function saveRetention(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); if (!retention) return; setSaving(true); try { setRetention(await request<ArtifactRetention>("/api/v1/artifacts/retention-settings", { method: "PUT", body: JSON.stringify({ clientCommandId: newClientCommandId(), expectedRowVersion: retention.rowVersion, generatedRetentionDays: retention.generatedRetentionDays }) })); } catch (reason) { setError(reason instanceof BackupError && reason.status === 409 ? "产物保留设置已被其他管理员修改，请刷新后重试。" : text(reason)); } finally { setSaving(false); } }
  return <section className="space-y-6"><div className="flex justify-between"><h2 className="text-xl font-semibold">备份与保留</h2><Button disabled={suspended} onClick={() => void trigger()}>立即备份</Button></div>{error && <Alert variant="destructive"><AlertDescription>{error}</AlertDescription></Alert>}
    {settings && <form className="space-y-3 rounded border p-4" onSubmit={saveSettings}><h3 className="font-semibold">备份设置</h3><Field orientation="horizontal"><input id="backup-enabled" type="checkbox" checked={settings.enabled} disabled={suspended || saving} onChange={event => setSettings(current => current && { ...current, enabled: event.target.checked })}/><FieldLabel htmlFor="backup-enabled">启用计划备份</FieldLabel></Field><Field><FieldLabel htmlFor="backup-cron">Cron</FieldLabel><Input id="backup-cron" value={settings.scheduleCron ?? ""} disabled={suspended || saving} placeholder="留空仅手动" onChange={event => setSettings(current => current && { ...current, scheduleCron: event.target.value })}/></Field><Field><FieldLabel htmlFor="backup-timezone">时区</FieldLabel><Input id="backup-timezone" value={settings.timezone} disabled={suspended || saving} onChange={event => setSettings(current => current && { ...current, timezone: event.target.value })}/></Field><Field><FieldLabel htmlFor="backup-retention">保留份数</FieldLabel><Input id="backup-retention" type="number" min="1" value={settings.retentionCount} disabled={suspended || saving} onChange={event => setSettings(current => current && { ...current, retentionCount: Number(event.target.value) })}/><FieldDescription>目标：{settings.backupTarget}</FieldDescription></Field><Button type="submit" disabled={suspended || saving}>保存备份设置</Button></form>}
    {retention && <form className="space-y-3 rounded border p-4" onSubmit={saveRetention}><h3 className="font-semibold">生成型产物在线保留</h3><Field><FieldLabel htmlFor="artifact-retention">天数</FieldLabel><Input id="artifact-retention" type="number" min="1" value={retention.generatedRetentionDays} disabled={suspended || saving} onChange={event => setRetention(current => current && { ...current, generatedRetentionDays: Number(event.target.value) })}/><FieldDescription>只影响后续新建的生成型产物。</FieldDescription></Field><Button type="submit" disabled={suspended || saving}>保存产物保留</Button></form>}
    <section className="space-y-3"><h3 className="font-semibold">备份记录</h3><Table><TableHeader><TableRow><TableHead>ID</TableHead><TableHead>状态</TableHead><TableHead>阶段</TableHead><TableHead>创建时间</TableHead><TableHead /></TableRow></TableHeader><TableBody>{items.map(item => <TableRow key={item.id}><TableCell>{item.id}</TableCell><TableCell>{item.status}{item.errorDetail && <small className="block text-destructive">{item.errorDetail}</small>}</TableCell><TableCell>{item.stage}</TableCell><TableCell>{item.createdAt}</TableCell><TableCell>{item.status.toLowerCase() === "succeeded" && <a className="underline" href={`/api/v1/backups/${item.id}/download`}>下载归档</a>}</TableCell></TableRow>)}</TableBody></Table>{cursor && <Button variant="outline" onClick={() => void load(true)}>加载更多</Button>}</section>
  </section>;
}
