import { useEffect, useState } from "react";
import { Alert, AlertDescription } from "@/components/ui/alert";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Field, FieldDescription, FieldLabel } from "@/components/ui/field";
import { Input } from "@/components/ui/input";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { createUser, listUsers, messageOf, resetPassword, revokeSessions, type AdminUser, updateUser } from "../../../src/features/admin/users/api";
import { ConfirmAction } from "./controls";

/** Password drafts only live in component memory and are cleared after every command. */
export function Users({ suspended }: { suspended: boolean }) {
 const [items, setItems] = useState<AdminUser[]>([]); const [error, setError] = useState(""); const [creating, setCreating] = useState(false); const [resetting, setResetting] = useState<AdminUser>();
 const empty: { username: string; displayName: string; password: string; role: AdminUser["role"] } = { username: "", displayName: "", password: "", role: "operator" }; const [draft, setDraft] = useState(empty); const [temporaryPassword, setTemporaryPassword] = useState("");
 const load = async () => { try { setItems(await listUsers()); } catch (reason) { setError(messageOf(reason, "暂时无法读取用户。")); } };
 useEffect(() => { void load(); }, []);
 async function create() { try { await createUser(draft); setCreating(false); setDraft(empty); await load(); } catch (reason) { setError(messageOf(reason, "暂时无法创建用户。")); } finally { setDraft(value => ({ ...value, password: "" })); } }
 async function update(user: AdminUser, changes: Parameters<typeof updateUser>[2]) { try { await updateUser(user.id, user.rowVersion, changes); await load(); } catch (reason) { setError(messageOf(reason, "暂时无法更新用户。")); } }
 async function reset() { if (!resetting) return; try { await resetPassword(resetting.id, resetting.rowVersion, temporaryPassword); setResetting(undefined); await load(); } catch (reason) { setError(messageOf(reason, "暂时无法重置密码。")); } finally { setTemporaryPassword(""); } }
 return <section className="space-y-4"><div className="flex justify-between"><h2 className="text-xl font-semibold">用户</h2><Button disabled={suspended} onClick={() => setCreating(true)}>新建用户</Button></div>{error && <Alert variant="destructive"><AlertDescription>{error}</AlertDescription></Alert>}<Table><TableHeader><TableRow><TableHead>用户</TableHead><TableHead>角色</TableHead><TableHead>状态</TableHead><TableHead /></TableRow></TableHeader><TableBody>{items.map(user => <TableRow key={user.id}><TableCell>{user.displayName}<small className="block text-muted-foreground">{user.username}</small></TableCell><TableCell><Select value={user.role} disabled={suspended} onValueChange={role => void update(user, { role: role as AdminUser["role"] })}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="admin">admin</SelectItem><SelectItem value="operator">operator</SelectItem></SelectContent></Select></TableCell><TableCell><Badge variant={user.enabled ? "default" : "secondary"}>{user.enabled ? "已启用" : "已停用"}</Badge></TableCell><TableCell className="space-x-2"><Button size="sm" variant="outline" disabled={suspended} onClick={() => void update(user, { enabled: !user.enabled })}>{user.enabled ? "停用" : "启用"}</Button><Button size="sm" variant="outline" disabled={suspended} onClick={() => setResetting(user)}>重置密码</Button><ConfirmAction title="撤销该用户的所有会话？" description="该用户需要重新登录后才能继续使用工作台。" disabled={suspended} onConfirm={() => void revokeSessions(user.id).then(load).catch(reason => setError(messageOf(reason, "暂时无法撤销会话。")))}>撤销会话</ConfirmAction></TableCell></TableRow>)}</TableBody></Table><Dialog open={creating} onOpenChange={setCreating}><DialogContent><DialogHeader><DialogTitle>新建用户</DialogTitle><DialogDescription>临时密码仅随这次提交发送，界面不会保存或回显。</DialogDescription></DialogHeader><UserFields draft={draft} setDraft={setDraft} /><Button disabled={suspended || !draft.username || !draft.displayName || draft.password.length < 15} onClick={() => void create()}>创建用户</Button></DialogContent></Dialog><Dialog open={Boolean(resetting)} onOpenChange={open => { if (!open) { setResetting(undefined); setTemporaryPassword(""); } }}><DialogContent><DialogHeader><DialogTitle>重置密码</DialogTitle><DialogDescription>临时密码只在本次提交中使用，成功后会撤销现有会话。</DialogDescription></DialogHeader><Field><FieldLabel>新临时密码</FieldLabel><Input type="password" autoComplete="new-password" value={temporaryPassword} onChange={event => setTemporaryPassword(event.target.value)} /></Field><Button disabled={suspended || temporaryPassword.length < 15} onClick={() => void reset()}>重置并撤销会话</Button></DialogContent></Dialog></section>;
}
function UserFields({ draft, setDraft }: { draft: { username: string; displayName: string; password: string; role: AdminUser["role"] }; setDraft: React.Dispatch<React.SetStateAction<{ username: string; displayName: string; password: string; role: AdminUser["role"] }>> }) { return <><Field><FieldLabel>用户名</FieldLabel><Input value={draft.username} onChange={event => setDraft(value => ({ ...value, username: event.target.value }))} /></Field><Field><FieldLabel>显示名称</FieldLabel><Input value={draft.displayName} onChange={event => setDraft(value => ({ ...value, displayName: event.target.value }))} /></Field><Field><FieldLabel>角色</FieldLabel><Select value={draft.role} onValueChange={role => setDraft(value => ({ ...value, role: role as AdminUser["role"] }))}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="operator">operator</SelectItem><SelectItem value="admin">admin</SelectItem></SelectContent></Select></Field><Field><FieldLabel>临时密码</FieldLabel><Input type="password" autoComplete="new-password" value={draft.password} onChange={event => setDraft(value => ({ ...value, password: event.target.value }))} /><FieldDescription>至少 15 个字符。</FieldDescription></Field></>; }
