import { useEffect, useState } from "react";
import { Alert, AlertDescription } from "@/components/ui/alert";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { cancelDeploymentVerification, fetchDeploymentVerification, fetchDeploymentVerifications, startDeploymentVerification, type DeploymentVerificationDetail } from "../../../src/features/admin/verification/api";
import { ConfirmAction } from "./controls";

/** Detail remains a server projection: item stages, provenance, conflicts, and drift are never inferred locally. */
export function Verification({ suspended }: { suspended: boolean }) {
 const [items, setItems] = useState<DeploymentVerificationDetail[]>([]); const [cursor, setCursor] = useState<string>(); const [selected, setSelected] = useState<DeploymentVerificationDetail>(); const [error, setError] = useState("");
 const load = async (more = false) => { try { const page = await fetchDeploymentVerifications(more ? cursor : undefined); setItems(current => more ? [...current, ...page.items as DeploymentVerificationDetail[]] : page.items as DeploymentVerificationDetail[]); setCursor(page.nextCursor); } catch (reason) { setError(reason instanceof Error ? reason.message : "暂时无法读取部署验证。 "); } };
 useEffect(() => { queueMicrotask(() => { void load(); }); }, []);
 const detail = async (id: string) => { try { setSelected(await fetchDeploymentVerification(id)); } catch (reason) { setError(reason instanceof Error ? reason.message : "暂时无法读取验证详情。"); } };
 const replace = (value: DeploymentVerificationDetail) => { setSelected(value); setItems(current => current.map(item => item.id === value.id ? value : item)); };
 return <section className="space-y-4"><div className="flex justify-between"><h2 className="text-xl font-semibold">部署验证</h2><Button disabled={suspended} onClick={() => void startDeploymentVerification().then(value => { replace(value); }).catch(reason => setError(reason instanceof Error ? reason.message : "无法启动部署验证。"))}>开始验证</Button></div>{error && <Alert variant="destructive"><AlertDescription>{error}</AlertDescription></Alert>}<Table><TableHeader><TableRow><TableHead>验证</TableHead><TableHead>进度</TableHead><TableHead>开始时间</TableHead><TableHead /></TableRow></TableHeader><TableBody>{items.map(item => <TableRow key={item.id}><TableCell>{item.id}<small className="block text-muted-foreground">{item.catalogDigest}</small></TableCell><TableCell>{progressLabel(item.progress)} · {item.itemCount} 项</TableCell><TableCell>{item.startedAt}</TableCell><TableCell className="space-x-2"><Button size="sm" variant="outline" onClick={() => void detail(item.id)}>详情</Button><ConfirmAction title="取消此部署验证？" description="取消后会由服务端为仍在执行的验证建立取消栅栏。" disabled={suspended || Boolean(item.receipt)} onConfirm={() => void cancelDeploymentVerification(item.id).then(replace).catch(reason => setError(reason instanceof Error ? reason.message : "无法取消部署验证。"))}>取消</ConfirmAction></TableCell></TableRow>)}</TableBody></Table>{cursor && <Button variant="outline" onClick={() => void load(true)}>加载更多</Button>}{selected && <VerificationDetail detail={selected} />}</section>;
}
function VerificationDetail({ detail }: { detail: DeploymentVerificationDetail }) { return <section className="space-y-3 rounded border p-4"><div className="flex items-center justify-between"><h3 className="font-semibold">验证详情 {detail.id}</h3>{detail.receipt && <Badge>{detail.receipt.overallOutcome}</Badge>}</div><p className="text-sm text-muted-foreground">清单 {detail.manifestDigest} · 条目集 {detail.itemSetDigest}</p><h4 className="font-medium">阶段与来源</h4><Table><TableHeader><TableRow><TableHead>场景</TableHead><TableHead>对象</TableHead><TableHead>输入</TableHead><TableHead>结果来源</TableHead><TableHead>结果</TableHead></TableRow></TableHeader><TableBody>{detail.items.map(item => { const result = detail.results.find(candidate => candidate.itemId === item.id); return <TableRow key={item.id}><TableCell>{item.scenarioId}<small className="block text-muted-foreground">{item.cellId}</small></TableCell><TableCell>{item.objectKind}</TableCell><TableCell className="break-all text-xs">{item.inputDigest}</TableCell><TableCell>{result?.producerType ?? "等待结果"}</TableCell><TableCell>{result ? <Badge variant={result.outcome === "failed" ? "destructive" : "secondary"}>{result.outcome} · {result.category}</Badge> : "未完成"}</TableCell></TableRow>; })}</TableBody></Table>{detail.conflicts.length > 0 && <><h4 className="font-medium">结果冲突</h4>{detail.conflicts.map(conflict => <p key={conflict.id} className="text-sm">条目 {conflict.itemId}：{conflict.firstResultId} 与 {conflict.conflictingResultId}</p>)}</>}{detail.subjectDrifts.length > 0 && <><h4 className="font-medium">主体漂移</h4>{detail.subjectDrifts.map(drift => <p key={`${drift.itemId}-${drift.driftField}`} className="break-all text-sm">条目 {drift.itemId} · {drift.driftField}：冻结 {drift.frozenDigest}，当前 {drift.currentDigest}</p>)}</>}</section>; }

function progressLabel(value: unknown): string {
 if (!value || typeof value !== "object") return "进度未知";
 const record = value as Record<string, unknown>;
 return typeof record.completed === "number" && typeof record.total === "number" ? `${record.completed}/${record.total}` : "进度未知";
}
