import { useCallback, useEffect, useRef, useState } from 'react'
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from '@/components/ui/accordion'
import { Collapsible, CollapsibleContent, CollapsibleTrigger } from '@/components/ui/collapsible'
import { AssistantMessageAccumulator, UIMessageStreamDecoder } from 'assistant-stream'
import { Alert, AlertDescription } from '@/components/ui/alert'
import { Badge } from '@/components/ui/badge'
import { Button } from '@/components/ui/button'
import { Dialog, DialogContent, DialogHeader, DialogTitle } from '@/components/ui/dialog'
import { Input } from '@/components/ui/input'
import { ScrollArea } from '@/components/ui/scroll-area'
import { Textarea } from '@/components/ui/textarea'
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table'
import type { WorkspaceModuleProps, WorkspaceModuleView } from '../../module-contract'
import { api, sourceLabel, type InvestigationAttempt, type InvestigationDetail, type InvestigationMessage, type InvestigationSummary } from '../../../src/features/investigation/api'
import { attachmentCommandId, uploadAttachment, type TextAttachmentSummary } from '../../../src/features/investigation/attachments/api'
import { listToolCalls, type ToolCallItem } from '../../../src/features/investigation/tools/api'
import { appendFeedback, feedbackValueLabels, fetchFeedback, type FeedbackEvent, type FeedbackValue } from '../../../src/features/feedback/api'
import { api as knowledgeApi } from '../../../src/features/knowledge/api'
const text = (reason: unknown, fallback: string) => reason instanceof Error ? reason.message : fallback
const when = (value: string) => new Date(value).toLocaleString()
const routeParts = (route: string) => new URL(route, 'https://workbench.invalid')

export function useInvestigationsModule(props: WorkspaceModuleProps): WorkspaceModuleView {
  const route = routeParts(props.route); const id = route.pathname.match(/^\/investigations\/([^/]+)$/)?.[1]
  const [items, setItems] = useState<InvestigationSummary[]>([]); const [error, setError] = useState('')
  const load = useCallback(async () => { if (props.suspended) return; try { setItems((await api.list()).items); setError('') } catch (reason) { setError(text(reason, '无法加载调查。')) } }, [props.suspended])
  useEffect(() => { void Promise.resolve().then(load) }, [load])
  const list = <aside className="space-y-3 p-3"><Button className="w-full" size="sm" onClick={() => props.navigate('/investigations/new')}>新建调查</Button>{error && <Alert variant="destructive"><AlertDescription>{error}</AlertDescription></Alert>}{items.length === 0 ? <p className="text-sm text-muted-foreground">尚无调查。</p> : items.map((item) => <button key={item.id} className="w-full rounded border p-3 text-left hover:bg-accent" onClick={() => props.navigate(`/investigations/${encodeURIComponent(item.id)}`)}><strong className="block truncate">{item.displayTitle}</strong><small>{when(item.lastActivityAt)}</small></button>)}</aside>
  const content = route.pathname === '/investigations/new' ? <NewInvestigation {...props}/> : id ? <InvestigationView key={id} id={id} {...props}/> : <section className="p-6"><h1 className="text-xl font-semibold">调查</h1><p className="mt-2 text-sm text-muted-foreground">从左侧创建或打开调查。</p></section>
  return { title: '调查', list, content }
}
function NewInvestigation({ route, navigate, suspended }: WorkspaceModuleProps) {
  const query = routeParts(route).searchParams; const occurrence = query.get('occurrence'); const analysis = query.get('initialAnalysis'); const [body, setBody] = useState(''); const [files, setFiles] = useState<TextAttachmentSummary[]>([]); const [error, setError] = useState(''); const [busy, setBusy] = useState(false)
  const create = async () => { if (!body.trim() && files.length === 0) return setError('请输入第一条消息或添加附件。'); setBusy(true); try { const sources = occurrence ? [{ type: 'occurrence', sourceId: occurrence }, ...(analysis ? [{ type: 'initial_analysis', sourceId: analysis }] : [])] : []; const item = await api.create(body, sources, files.map((file) => file.id)); navigate(`/investigations/${encodeURIComponent(item.id)}`) } catch (reason) { setError(text(reason, '无法创建调查。')) } finally { setBusy(false) } }
  return <section className="max-w-3xl space-y-4 p-6"><h1 className="text-xl font-semibold">新建调查</h1>{occurrence && <Alert><AlertDescription>将关联告警 {occurrence}{analysis ? ' 与初步分析' : ''}。</AlertDescription></Alert>}<Textarea value={body} onChange={(event) => setBody(event.target.value)} disabled={suspended || busy} placeholder="描述需要调查的问题…"/><Attachments files={files} setFiles={setFiles} disabled={suspended || busy}/>{error && <Alert variant="destructive"><AlertDescription>{error}</AlertDescription></Alert>}<Button disabled={suspended || busy} onClick={() => void create()}>{busy ? '正在创建…' : '创建并发送'}</Button></section>
}
function InvestigationView({ id, suspended, openEvidence, navigate }: WorkspaceModuleProps & { id: string }) {
  const [detail, setDetail] = useState<InvestigationDetail | null>(null); const [messages, setMessages] = useState<InvestigationMessage[]>([]); const [attempts, setAttempts] = useState<InvestigationAttempt[]>([]); const [error, setError] = useState('')
  const load = useCallback(async () => { if (suspended) return; try { const [next, messagePage, attemptPage] = await Promise.all([api.get(id), api.listMessages(id), api.listAttempts(id)]); setDetail(next); setMessages(messagePage.items); setAttempts(attemptPage.items); setError('') } catch (reason) { setError(text(reason, '无法加载调查。')) } }, [id, suspended])
  useEffect(() => { void Promise.resolve().then(load) }, [load])
  if (!detail) return <section className="p-6">{error ? <Alert variant="destructive"><AlertDescription>{error}</AlertDescription></Alert> : <p className="text-sm text-muted-foreground">正在加载调查…</p>}</section>
  return <section className="flex min-h-0 flex-1 flex-col gap-4 p-6"><header><h1 className="text-xl font-semibold">{detail.displayTitle}</h1><div className="mt-2 flex flex-wrap gap-2">{detail.sources.map((source) => <Badge key={`${source.type}-${source.sourceId}`} variant="outline">{sourceLabel(source.type)} {source.sourceId}</Badge>)}</div></header>{error && <Alert variant="destructive"><AlertDescription>{error}</AlertDescription></Alert>}<Thread detail={detail} messages={messages} attempts={attempts} suspended={suspended} openEvidence={openEvidence} navigate={navigate} reload={load}/></section>
}
function Thread({ detail, messages, attempts, suspended, openEvidence, navigate, reload }: { detail: InvestigationDetail; messages: InvestigationMessage[]; attempts: InvestigationAttempt[]; suspended: boolean; openEvidence: (id: string) => void; navigate: (route: string) => void; reload: () => Promise<void> }) {
  const [body, setBody] = useState(''); const [files, setFiles] = useState<TextAttachmentSummary[]>([]); const [error, setError] = useState(''); const [busy, setBusy] = useState(false); const [tools, setTools] = useState<ToolCallItem[]>([]); const [events, setEvents] = useState<FeedbackEvent[]>([]); const [streamText, setStreamText] = useState(''); const controller = useRef<AbortController | null>(null)
  const active = attempts.find((item) => ['Queued', 'Assigned', 'Running', 'Cancelling'].includes(item.state))
  useEffect(() => { if (!active || suspended) return; const timer = window.setInterval(() => void reload(), 2000); return () => window.clearInterval(timer) }, [active, reload, suspended])
  useEffect(() => () => { controller.current?.abort() }, [])
  const send = async () => { if (!body.trim() && files.length === 0) return; setBusy(true); setStreamText(''); try { const sent = await api.sendMessage(detail.id, body, detail.headMessageId ?? null, files.map((file) => file.id)); setBody(''); setFiles([]); controller.current = new AbortController(); await stream(detail.id, sent.id, controller.current.signal, setStreamText); await reload() } catch (reason) { if (!(reason instanceof DOMException && reason.name === 'AbortError')) setError(text(reason, '消息发送失败。')) } finally { controller.current = null; setStreamText(''); setBusy(false) } }
  const cancel = async () => { if (!active) return; setBusy(true); try { await api.cancelAttempt(detail.id, active.id, active.rowVersion); controller.current?.abort(); await reload() } catch (reason) { setError(text(reason, '无法停止。')) } finally { setBusy(false) } }
  return <><ScrollArea className="min-h-72 flex-1 rounded border p-4"><div className="space-y-4">{messages.map((message) => <Message key={message.id} message={message} attempts={attempts} investigationId={detail.id} openEvidence={openEvidence} navigate={navigate} showTools={setTools} showEvents={setEvents}/>) }{streamText && <article aria-live="polite" className="rounded border border-primary/30 p-3"><Badge variant="outline">助手正在回复</Badge><p className="mt-2 whitespace-pre-wrap text-sm">{streamText}</p></article>}</div></ScrollArea>{active && <Button variant="outline" size="sm" disabled={suspended || busy} onClick={() => void cancel()}>停止 {active.state}</Button>}{tools.length > 0 && <ToolCalls items={tools}/>}<Textarea value={body} onChange={(event) => setBody(event.target.value)} disabled={suspended || busy || !!active} placeholder="输入消息…"/><Attachments files={files} setFiles={setFiles} disabled={suspended || busy || !!active}/>{error && <p role="alert" className="text-sm text-destructive">{error}</p>}<div className="flex gap-2"><Button disabled={suspended || busy || !!active} onClick={() => void send()}>发送</Button>{detail.headMessageId && !active && <Button variant="outline" disabled={suspended || busy} onClick={() => { setBusy(true); api.undo(detail.id, detail.headMessageId!).then(reload).catch((reason: unknown) => setError(text(reason, '无法撤回。'))).finally(() => setBusy(false)) }}>撤回最近回合</Button>}{attempts.filter((item) => item.state === 'Failed').map((item) => <Button key={item.id} variant="outline" size="sm" disabled={suspended || busy} onClick={() => { setBusy(true); api.retryAttempt(detail.id, item.id).then(reload).catch((reason: unknown) => setError(text(reason, '无法重试。'))).finally(() => setBusy(false)) }}>重试</Button>)}</div>{events.length > 0 && <p className="text-xs text-muted-foreground">反馈：{events.map((event) => feedbackValueLabels[event.value]).join('、')}</p>}</>
}
async function stream(investigationId: string, messageId: string, signal: AbortSignal, onText: (text: string) => void) { const response = await fetch(`/api/v1/investigations/${encodeURIComponent(investigationId)}/messages/${encodeURIComponent(messageId)}/stream`, { method: 'POST', credentials: 'include', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ clientCommandId: crypto.randomUUID(), protocol: 'ui-message-stream' }), signal }); if (!response.ok || !response.body) throw new Error('回复流不可用，请重试。'); const reader = response.body.pipeThrough(new UIMessageStreamDecoder()).pipeThrough(new AssistantMessageAccumulator()).getReader(); try { while (true) { const { done, value } = await reader.read(); if (done) break; const message = value as { content?: Array<{ type?: string; text?: string }> }; onText((message.content ?? []).filter((part) => part.type === 'text').map((part) => part.text ?? '').join('')) } } finally { reader.releaseLock() } }
function Message({ message, attempts, investigationId, openEvidence, navigate, showTools, showEvents }: { message: InvestigationMessage; attempts: InvestigationAttempt[]; investigationId: string; openEvidence: (id: string) => void; navigate: (route: string) => void; showTools: (items: ToolCallItem[]) => void; showEvents: (items: FeedbackEvent[]) => void }) { const [error, setError] = useState(''); const attempt = message.attemptId ? attempts.find((item) => item.id === message.attemptId) : undefined; const feedback = async (value: FeedbackValue) => { try { await appendFeedback({ type: 'investigation_message', id: message.id }, value, ''); showEvents((await fetchFeedback({ type: 'investigation_message', id: message.id })).items) } catch (reason) { setError(text(reason, '无法提交反馈。')) } }; return <article className="rounded border p-3"><Badge variant="outline">{message.role === 'user' ? '你' : '助手'}</Badge><p className="mt-2 whitespace-pre-wrap text-sm">{message.content}</p>{attempt && <p className="text-xs text-muted-foreground">执行：{attempt.state}</p>}{message.evidenceIds?.map((id) => <Button className="mt-2 mr-2" key={id} size="sm" variant="outline" onClick={() => openEvidence(id)}>证据 {id}</Button>)}{message.attemptId && <Button className="mt-2" size="sm" variant="ghost" onClick={() => { listToolCalls(investigationId, message.attemptId!).then(showTools).catch((reason: unknown) => setError(text(reason, '无法读取工具调用。'))) }}>工具调用</Button>}{message.role === 'assistant' && <div className="mt-2 flex flex-wrap gap-1">{(['adopted', 'executed', 'verified_effective', 'rejected'] as FeedbackValue[]).map((value) => <Button key={value} size="sm" variant="ghost" onClick={() => void feedback(value)}>{feedbackValueLabels[value]}</Button>)}<Button size="sm" variant="ghost" onClick={() => { knowledgeApi.createMessageCandidate(investigationId, message.id).then((item) => navigate(`/knowledge/candidates/${encodeURIComponent(item.id)}`)).catch((reason: unknown) => setError(text(reason, '无法创建知识候选。'))) }}>整理为知识</Button></div>}{error && <p role="alert" className="text-sm text-destructive">{error}</p>}</article> }
function ToolCalls({ items }: { items: ToolCallItem[] }) { return <Accordion type="single" collapsible><AccordionItem value="tools"><AccordionTrigger>工具调用（{items.length}）</AccordionTrigger><AccordionContent>{items.map((item) => <Collapsible className="mb-2 rounded border p-2" key={item.id}><CollapsibleTrigger className="w-full text-left text-sm font-medium">{item.toolName} · {item.status}</CollapsibleTrigger><CollapsibleContent className="mt-2"><Table><TableHeader><TableRow><TableHead>字段</TableHead><TableHead>值</TableHead></TableRow></TableHeader><TableBody><TableRow><TableCell>执行模式</TableCell><TableCell>{item.executionMode}</TableCell></TableRow><TableRow><TableCell>失败模式</TableCell><TableCell>{item.failureMode}</TableCell></TableRow>{item.errorDetail && <TableRow><TableCell>错误</TableCell><TableCell>{item.errorDetail}</TableCell></TableRow>}</TableBody></Table><Accordion type="single" collapsible><AccordionItem value="raw"><AccordionTrigger>原始参数与结果</AccordionTrigger><AccordionContent><pre className="overflow-x-auto text-xs">{JSON.stringify({ arguments: item.arguments, result: item.result }, null, 2)}</pre></AccordionContent></AccordionItem></Accordion></CollapsibleContent></Collapsible>)}</AccordionContent></AccordionItem></Accordion> }
function Attachments({ files, setFiles, disabled }: { files: TextAttachmentSummary[]; setFiles: (files: TextAttachmentSummary[]) => void; disabled: boolean }) { const [preview, setPreview] = useState<TextAttachmentSummary | null>(null); const [body, setBody] = useState(''); useEffect(() => { if (!preview || preview.bodyExpired) return; fetch(`/api/v1/artifacts/${encodeURIComponent(preview.artifactId)}/content`, { credentials: 'include' }).then((response) => response.ok ? response.text() : Promise.reject()).then(setBody).catch(() => setBody('预览不可用。')) }, [preview]); return <div className="space-y-2"><Input type="file" disabled={disabled} onChange={(event) => { const file = event.target.files?.[0]; event.currentTarget.value = ''; if (file) uploadAttachment(file, attachmentCommandId()).then((item) => setFiles([...files, item])) }} />{files.map((file) => <div key={file.id} className="flex justify-between rounded border p-2 text-sm"><span>{file.originalFilename}</span><span><Button type="button" size="sm" variant="ghost" onClick={() => setPreview(file)}>预览</Button><Button type="button" size="sm" variant="ghost" onClick={() => setFiles(files.filter((item) => item.id !== file.id))}>移除</Button></span></div>)}<Dialog open={!!preview} onOpenChange={(open) => { if (!open) setPreview(null) }}><DialogContent className="max-w-2xl"><DialogHeader><DialogTitle>{preview?.originalFilename}</DialogTitle></DialogHeader>{preview?.bodyExpired ? <p>附件正文已清理。</p> : <ScrollArea className="h-80 border"><pre className="whitespace-pre-wrap p-3 text-xs">{body}</pre></ScrollArea>}</DialogContent></Dialog></div> }
