/* eslint-disable react-refresh/only-export-components -- parsing is colocated with the YAML editor. */
import { useEffect, useMemo, useState } from "react";
import { parse as parseYaml, stringify as stringifyYaml } from "yaml";
import { Alert, AlertDescription } from "@/components/ui/alert";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Field, FieldDescription, FieldGroup, FieldLabel } from "@/components/ui/field";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Textarea } from "@/components/ui/textarea";
import { messageOf } from "@/app/shared";
import { listAlertmanagerInstances, listMetricsInstances, type AlertmanagerInstance, type MetricsInstance } from "@/features/integrations/api";
import { getBusinessSystem, getConfigVersion, listConfigVersions, uploadBusinessSystemConfig, type ConfigVersionDetail } from "@/features/admin/business-systems/api";

export type LabelMap = Record<string, string>;
export interface Declaration {
  apiVersion: "quoin/v1";
  kind: "BusinessSystem";
  metadata: { name: string; displayName: string; description: string };
  spec: {
    metrics: { connectionRef: string; matchLabels: LabelMap; resources: Array<{ name: string; displayName: string; matchLabels: LabelMap; discoveryMetric: string; identityLabels: string[]; allowedMetrics: string[] }> };
    /** Optional in the compiler schema; omitted declarations default to enabled. */
    enabled?: boolean;
    alerts: { sourceRefs: string[]; matchLabels: LabelMap };
    inspections: Array<{ name: string; displayName: string; schedule: string; timezone: string; checks: Array<{ name: string; resourceRef: string; expression: string; question: string; queryMode?: "instant" | "range"; rangeSeconds?: number; stepSeconds?: number }> }>;
    discovery?: { refresh?: string };
  };
}

const isObject = (value: unknown): value is Record<string, unknown> => Boolean(value) && typeof value === "object" && !Array.isArray(value);
const stringMap = (value: unknown, name: string): LabelMap => { if (!isObject(value) || Object.values(value).some((item) => typeof item !== "string" || !item)) throw new Error(`${name} 必须是非空字符串映射。`); return value as LabelMap; };
const strings = (value: unknown, name: string, requireItems = true): string[] => { if (!Array.isArray(value) || (requireItems && value.length === 0) || value.some((item) => typeof item !== "string" || !item)) throw new Error(`${name} 必须是${requireItems ? "非空" : ""}字符串数组。`); return value as string[]; };
const text = (value: unknown, name: string): string => { if (typeof value !== "string" || !value.trim()) throw new Error(`${name} 不能为空。`); return value; };
const defaultDeclaration = (connectionRef = "", sourceRefs: string[] = []): Declaration => ({ apiVersion: "quoin/v1", kind: "BusinessSystem", metadata: { name: "", displayName: "", description: "" }, spec: { enabled: true, metrics: { connectionRef, matchLabels: { service: "example" }, resources: [{ name: "workloads", displayName: "工作负载", matchLabels: { app: "example" }, discoveryMetric: "up", identityLabels: ["namespace", "pod"], allowedMetrics: ["up"] }] }, alerts: { sourceRefs, matchLabels: {} }, inspections: [{ name: "health", displayName: "健康检查", schedule: "*/5 * * * *", timezone: "Asia/Shanghai", checks: [{ name: "availability", resourceRef: "workloads", expression: "up", question: "服务是否可用？" }] }], discovery: { refresh: "5m" } } });

/** Performs local structural checks only; backend remains authoritative for schema and scoped PromQL validation. */
export function parseDeclaration(yaml: string): Declaration {
  const root = parseYaml(yaml);
  if (!isObject(root) || root.apiVersion !== "quoin/v1" || root.kind !== "BusinessSystem") throw new Error("声明必须包含 apiVersion: quoin/v1 和 kind: BusinessSystem。");
  const metadata = root.metadata; const spec = root.spec;
  if (!isObject(metadata) || !isObject(spec) || !isObject(spec.metrics) || !isObject(spec.alerts) || !Array.isArray(spec.inspections)) throw new Error("声明必须包含 metadata、spec.metrics、spec.alerts 和 spec.inspections。");
  const metrics = spec.metrics; const alerts = spec.alerts;
  if (!Array.isArray(metrics.resources)) throw new Error("spec.metrics.resources 必须是数组。");
  const resources = metrics.resources.map((value, index) => { if (!isObject(value)) throw new Error(`resources[${index}] 必须是对象。`); return { name: text(value.name, "资源 name"), displayName: text(value.displayName, "资源 displayName"), matchLabels: stringMap(value.matchLabels, "资源 matchLabels"), discoveryMetric: text(value.discoveryMetric, "资源 discoveryMetric"), identityLabels: strings(value.identityLabels, "资源 identityLabels"), allowedMetrics: strings(value.allowedMetrics, "资源 allowedMetrics") }; });
  const inspections = spec.inspections.map((value, index) => { if (!isObject(value) || !Array.isArray(value.checks)) throw new Error(`inspections[${index}] 必须包含 checks。`); return { name: text(value.name, "巡检 name"), displayName: text(value.displayName, "巡检 displayName"), schedule: text(value.schedule, "巡检 schedule"), timezone: text(value.timezone, "巡检 timezone"), checks: value.checks.map((check, checkIndex) => { if (!isObject(check)) throw new Error(`checks[${checkIndex}] 必须是对象。`); const queryMode: "instant" | "range" | undefined = check.queryMode === undefined ? undefined : check.queryMode === "instant" || check.queryMode === "range" ? check.queryMode : (() => { throw new Error("queryMode 必须是 instant 或 range。"); })(); return { name: text(check.name, "检查 name"), resourceRef: text(check.resourceRef, "检查 resourceRef"), expression: text(check.expression, "检查 expression"), question: text(check.question, "检查 question"), ...(queryMode ? { queryMode } : {}), ...(typeof check.rangeSeconds === "number" ? { rangeSeconds: check.rangeSeconds } : {}), ...(typeof check.stepSeconds === "number" ? { stepSeconds: check.stepSeconds } : {}) }; }) }; });
  if (spec.enabled !== undefined && typeof spec.enabled !== "boolean") throw new Error("spec.enabled 必须是布尔值。");
  return { apiVersion: "quoin/v1", kind: "BusinessSystem", metadata: { name: text(metadata.name, "metadata.name"), displayName: text(metadata.displayName, "metadata.displayName"), description: typeof metadata.description === "string" ? metadata.description : "" }, spec: { ...(typeof spec.enabled === "boolean" ? { enabled: spec.enabled } : {}), metrics: { connectionRef: text(metrics.connectionRef, "metrics.connectionRef"), matchLabels: stringMap(metrics.matchLabels, "metrics.matchLabels"), resources }, alerts: { sourceRefs: strings(alerts.sourceRefs, "alerts.sourceRefs", false), matchLabels: stringMap(alerts.matchLabels, "alerts.matchLabels") }, inspections, ...(isObject(spec.discovery) && typeof spec.discovery.refresh === "string" ? { discovery: { refresh: spec.discovery.refresh } } : {}) } };
}
export const declarationYaml = (declaration: Declaration) => stringifyYaml(declaration);

function CompiledPreview({ declaration }: { declaration: Declaration }) {
  return <div className="rounded border bg-muted/30 p-3 text-sm" aria-label="编译预览"><h3 className="font-medium">编译预览</h3><p className="mt-1 text-muted-foreground">关联与查询权限由声明直接生成，提交前仍由服务端校验。</p><ul className="mt-2 space-y-2">{declaration.spec.metrics.resources.map((resource) => <li key={resource.name}><strong>{resource.displayName}</strong> · 接入 {declaration.spec.metrics.connectionRef}<br />必需标签：{Object.entries({ ...declaration.spec.metrics.matchLabels, ...resource.matchLabels }).map(([key, value]) => `${key}=${value}`).join(", ")}<br />允许指标：{resource.allowedMetrics.join(", ")}</li>)}</ul>{declaration.spec.inspections.flatMap((inspection) => inspection.checks.map((check) => <p className="mt-2" key={`${inspection.name}/${check.name}`}>{inspection.displayName} / {check.name} → {check.resourceRef}: <code>{check.expression}</code></p>))}</div>;
}

export function DeclarationDraft({ suspended, onUploaded, navigate, editKey }: { suspended: boolean; onUploaded: (detail: ConfigVersionDetail) => void; navigate: (to: string) => void; editKey?: string }) {
  const [metrics, setMetrics] = useState<MetricsInstance[]>([]); const [sources, setSources] = useState<AlertmanagerInstance[]>([]); const [yaml, setYaml] = useState(""); const [parsed, setParsed] = useState<Declaration>(); const [loading, setLoading] = useState(Boolean(editKey)); const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  useEffect(() => { let cancelled = false; void Promise.all([listMetricsInstances(), listAlertmanagerInstances()]).then(([metricItems, sourceItems]) => { if (cancelled) return; const enabledMetrics = metricItems.filter((item) => item.status === "active"); const enabledSources = sourceItems.items.filter((item) => item.status === "active"); setMetrics(enabledMetrics); setSources(enabledSources); if (!editKey) { const initial = defaultDeclaration(enabledMetrics[0]?.displayName, enabledSources.map((item) => item.id)); setYaml(declarationYaml(initial)); setParsed(initial); } }).catch((reason) => !cancelled && setError(messageOf(reason, "无法读取可用接入。"))); return () => { cancelled = true; }; }, [editKey]);
  useEffect(() => { if (!editKey) { setLoading(false); return; } let cancelled = false; void Promise.all([getBusinessSystem(editKey), listConfigVersions(editKey)]).then(async ([system, versions]) => { const current = versions.find((item) => item.id === system.currentConfigVersionId) ?? versions[0]; if (!current) throw new Error("该业务没有可编辑的配置版本。"); const body = (await getConfigVersion(editKey, current.id)).yamlBody; const declaration = parseDeclaration(body); if (!cancelled) { setYaml(body); setParsed(declaration); } }).catch((reason) => !cancelled && setError(messageOf(reason, "无法读取现有业务声明。"))).finally(() => !cancelled && setLoading(false)); return () => { cancelled = true; }; }, [editKey]);
  const connectionNames = useMemo(() => metrics.map((item) => item.displayName), [metrics]);
  const apply = () => { try { const declaration = parseDeclaration(yaml); setParsed(declaration); setError(""); } catch (reason) { setParsed(undefined); setError(messageOf(reason, "YAML 无法解析。")); } };
  const template = (connectionRef: string) => { const declaration = defaultDeclaration(connectionRef, sources.map((item) => item.id)); setYaml(declarationYaml(declaration)); setParsed(declaration); setError(""); };
  const upload = async () => { try { const declaration = parseDeclaration(yaml); setBusy(true); const result = await uploadBusinessSystemConfig({ file: new File([yaml], `${declaration.metadata.name}.yaml`, { type: "application/yaml" }) }); onUploaded(result); } catch (reason) { setError(messageOf(reason, "无法创建业务草稿。")); } finally { setBusy(false); } };
  return <section className="mx-auto flex w-full max-w-5xl flex-col gap-5"><div className="flex flex-wrap items-end justify-between gap-3"><div><h2 className="text-xl font-semibold">{editKey ? "编辑业务声明" : "新建业务声明"}</h2><p className="mt-1 text-sm text-muted-foreground">以 Kubernetes 风格 YAML 管理业务范围、资源和巡检；连接与告警源使用已有名称。</p></div><Button variant="outline" onClick={() => navigate("/business-systems")}>返回业务列表</Button></div><Card><CardHeader><CardTitle>业务系统声明</CardTitle><CardDescription>YAML 是唯一提交来源。模板只填入可选的现有连接和告警源名称。</CardDescription></CardHeader><CardContent>{loading ? <p role="status">正在读取现有声明…</p> : <FieldGroup>{error && <Alert variant="destructive"><AlertDescription>{error}</AlertDescription></Alert>}<div className="grid gap-3 md:grid-cols-2"><Field><FieldLabel>从指标连接生成模板</FieldLabel><Select onValueChange={template} disabled={busy || suspended}><SelectTrigger aria-label="从指标连接生成模板"><SelectValue placeholder="选择连接名称" /></SelectTrigger><SelectContent>{connectionNames.map((name) => <SelectItem key={name} value={name}>{name}</SelectItem>)}</SelectContent></Select></Field><Field><FieldLabel>可用告警源</FieldLabel><div className="pt-2 text-sm text-muted-foreground">{sources.length ? sources.map((item) => item.id).join("，") : "暂无；模板会使用空 sourceRefs。"}</div></Field></div><Field><FieldLabel>权威 YAML 声明</FieldLabel><Textarea aria-label="权威 YAML 声明" value={yaml} onChange={(event) => setYaml(event.target.value)} className="min-h-[34rem] font-mono text-xs" disabled={busy || suspended} /><FieldDescription>包含 metadata、metrics、alerts、inspections 和可选 discovery.refresh。无需 Label Contract。</FieldDescription></Field><div className="flex flex-wrap gap-2"><Button type="button" variant="outline" onClick={apply} disabled={busy || suspended}>应用 YAML</Button><Button type="button" onClick={() => void upload()} disabled={busy || suspended}>{busy ? "正在创建…" : "创建版本化草稿"}</Button></div>{parsed && <CompiledPreview declaration={parsed} />}</FieldGroup>}</CardContent></Card></section>;
}
