import "@testing-library/jest-dom/vitest";
import { act, cleanup, fireEvent, render, screen } from "@testing-library/react";
import { afterEach, describe, expect, it, vi } from "vitest";
import { useKnowledgeModule } from "./index";

vi.mock("../../../src/features/knowledge/api", () => ({
  api: { browse: vi.fn().mockResolvedValue({ items: [], nextCursor: undefined }), search: vi.fn(), getCandidate: vi.fn(), editDraft: vi.fn(), confirm: vi.fn(), exclude: vi.fn(), getKnowledge: vi.fn(), listVersions: vi.fn(), getVersion: vi.fn(), createRevision: vi.fn(), stopReuse: vi.fn(), startImport: vi.fn(), getImportBatch: vi.fn(), confirmBatch: vi.fn(), cancelBatch: vi.fn() },
  candidateSourceLabels: { source_material: "导入原文" }, candidateStateLabels: { AwaitingConfirmation: "待确认" }, embeddingStateLabels: {}, indexStateLabels: {},
}));
function View({ route = "/knowledge", suspended = false }: { route?: string; suspended?: boolean }) { const view = useKnowledgeModule({ user: { id: "1", username: "a", displayName: "A", role: "admin", passwordChangeRequired: false, authRevision: 1, enabled: true, lastLoginAt: null, rowVersion: 1 }, route, suspended, navigate: vi.fn(), openEvidence: vi.fn() }); return <>{view.list}{view.content}</>; }
afterEach(() => { cleanup(); vi.clearAllMocks(); });
describe("knowledge module", () => { it("routes absolute knowledge candidates into the editor", async () => { const { api } = await import("../../../src/features/knowledge/api"); vi.mocked(api.getCandidate).mockResolvedValue({ id: "c1", sourceType: "source_material", sourceId: "s1", state: "AwaitingConfirmation", rowVersion: 1, generation: 1, draftRevision: 1, draftTitle: "候选", draftBody: "正文", originalSuggestion: { v: 1, source: { type: "source_material", id: "s1" }, title: "候选", body: "正文" } }); render(<View route="/knowledge/candidates/c1" />); expect(await screen.findByText("编辑知识候选")).toBeInTheDocument(); }); it("shows the real search distinction", async () => { const { api } = await import("../../../src/features/knowledge/api"); vi.mocked(api.search).mockResolvedValue({ mode: "query", exactTextMatches: [{ knowledge: { id: "1", title: "全文", currentVersionId: "v", currentVersionSeq: 1, eligible: true, rowVersion: 1 }, score: 1 }], semanticMatches: [{ knowledge: { id: "2", title: "语义", currentVersionId: "v2", currentVersionSeq: 1, eligible: true, rowVersion: 1 }, score: 0.7, indexState: "ready" }] }); render(<View />); fireEvent.change(await screen.findByLabelText("检索知识"), { target: { value: "cpu" } }); fireEvent.click(screen.getByRole("button", { name: "搜索" })); expect(await screen.findByText("全文匹配")).toBeInTheDocument(); expect(screen.getByText("语义相似")).toBeInTheDocument(); }); it("stops import polling while suspended", async () => { vi.useFakeTimers(); const { api } = await import("../../../src/features/knowledge/api"); vi.mocked(api.getImportBatch).mockResolvedValue({ id: "b", state: "Processing", rowVersion: 1, generation: 1, createdAt: "now", candidates: [] }); render(<View route="/imports/b" suspended />); await act(async () => {}); await act(async () => { vi.advanceTimersByTime(6000); }); expect(api.getImportBatch).toHaveBeenCalledTimes(1); vi.useRealTimers(); }); });
